In [16]:
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

tickers = ['NVDA', 'AAPL', 'GOOG', 'MSFT', 'AMZN',
           'META', 'AVGO', 'TSLA', 'WMT', 'LLY']
prices = yf.download(tickers, start="2020-01-01", end="2025-01-01")['Close']

[*********************100%***********************]  10 of 10 completed

In [21]:
prices.dropna(inplace=True)

In [27]:
returns = prices.pct_change(1)
returns.dropna(inplace=True)
returns.head()

Ticker,AAPL,AMZN,AVGO,GOOG,LLY,META,MSFT,NVDA,TSLA,WMT
Date,,,,,,,,,,
2020-01-03,-0.009722,-0.012139,-0.025435,-0.004907,-0.003328,-0.005291,-0.012452,-0.016006,0.029633,-0.008828
2020-01-06,0.007968,0.014886,-0.001496,0.024657,0.003719,0.018834,0.002585,0.004194,0.019255,-0.002036
2020-01-07,-0.004703,0.002092,-0.003443,-0.000624,0.001890,0.002164,-0.009118,0.012106,0.038801,-0.009264
2020-01-08,0.016087,-0.007809,-0.012474,0.007880,0.009056,0.010138,0.015928,0.001875,0.049205,-0.003432
2020-01-09,0.021241,0.004799,-0.008033,0.011044,0.016528,0.014311,0.012493,0.010983,-0.021945,0.010330

In [28]:
num_stocks = 10
weights = [1 / num_stocks] * num_stocks
print(weights)

[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [29]:
vcv_matrix = returns.cov(ddof=1)
vcv_matrix

Ticker,AAPL,AMZN,AVGO,GOOG,LLY,META,MSFT,NVDA,TSLA,WMT
Ticker,,,,,,,,,,
AAPL,0.000398,0.000268,0.000300,0.000264,0.000130,0.000318,0.000287,0.000411,0.000408,0.000103
AMZN,0.000268,0.000513,0.000292,0.000301,0.000110,0.000390,0.000295,0.000446,0.000415,0.000096
AVGO,0.000300,0.000292,0.000696,0.000279,0.000143,0.000346,0.000308,0.000591,0.000505,0.000087
GOOG,0.000264,0.000301,0.000279,0.000416,0.000113,0.000371,0.000291,0.000409,0.000346,0.000085
LLY,0.000130,0.000110,0.000143,0.000113,0.000421,0.000144,0.000145,0.000188,0.000065,0.000084
META,0.000318,0.000390,0.000346,0.000371,0.000144,0.000800,0.000337,0.000514,0.000397,0.000089
MSFT,0.000287,0.000295,0.000308,0.000291,0.000145,0.000337,0.000369,0.000445,0.000363,0.000104
NVDA,0.000411,0.000446,0.000591,0.000409,0.000188,0.000514,0.000445,0.001152,0.000670,0.000118
TSLA,0.000408,0.000415,0.000505,0.000346,0.000065,0.000397,0.000363,0.000670,0.001791,0.000094
WMT,0.000103,0.000096,0.000087,0.000085,0.000084,0.000089,0.000104,0.000118,0.000094,0.000202

In [32]:
var_p = np.dot(np.transpose(weights),
               np.dot(vcv_matrix, weights))
sd_p = np.sqrt(var_p)
print("Portfolio variance:", var_p)
print("Portfolio standard variation:", sd_p)

Portfolio variance: 0.00031679825342789366
Portfolio standard variation: 0.017798827304850554