## Estimating Portfolio Risk (Multiple Assets)

In [7]:
import pandas as pd
import numpy as np
from datetime import datetime

In [8]:
df = pd.read_csv('../data/10stocks_price.csv')

In [9]:
df.head()

,date_gsheets,AAPL,KO,NFLX,BRK.B,DIS,IBM,VZ,WMT,GE,TSLA
0,01/03/2012 16:00,58.75,35.07,10.32,77.68,38.31,186.30,39.73,60.33,18.36,28.08
1,01/04/2012 16:00,59.06,34.85,11.49,76.80,38.85,185.54,39.21,59.71,18.56,27.71
2,01/05/2012 16:00,59.72,34.69,11.33,76.93,39.50,184.66,38.94,59.42,18.55,27.12
3,01/06/2012 16:00,60.34,34.47,12.33,76.39,39.91,182.54,38.33,59.00,18.65,26.91
4,01/09/2012 16:00,60.25,34.47,14.03,76.29,39.75,181.59,38.37,59.18,18.86,27.25

In [10]:
type(df['date_gsheets'][0])

str

In [14]:
df['date_gsheets'][0]

'01/03/2012 16:00'

In [20]:
df['date_gsheets'] = pd.to_datetime(df['date_gsheets'], format='mixed')

In [22]:
df['date_gsheets'].describe()

count                          1509
mean     2015-01-02 13:11:34.234592
min             2012-01-03 16:00:00
25%             2013-07-05 16:00:00
50%             2015-01-02 16:00:00
75%             2016-07-01 16:00:00
max             2017-12-29 16:00:00
Name: date_gsheets, dtype: object

In [23]:
df.describe()

,date_gsheets,AAPL,KO,NFLX,BRK.B,DIS,IBM,VZ,WMT,GE,TSLA
count,1509,1509.000000,1509.000000,1509.000000,1509.000000,1509.000000,1509.000000,1509.000000,1509.000000,1509.000000,1509.000000
mean,2015-01-02 13:11:34.234592,102.874380,41.119881,77.348801,130.578032,84.278529,172.739881,47.687641,73.481365,25.564983,185.623453
min,2012-01-03 16:00:00,55.790000,33.490000,7.690000,76.290000,38.310000,117.850000,36.800000,56.420000,17.360000,22.790000
25%,2013-07-05 16:00:00,78.440000,38.900000,34.220000,112.700000,64.020000,154.000000,45.560000,69.120000,23.190000,117.820000
50%,2015-01-02 16:00:00,99.520000,41.170000,64.360000,134.140000,92.030000,173.480000,48.120000,73.780000,25.790000,207.830000
75%,2016-07-01 16:00:00,119.250000,43.000000,110.100000,146.690000,104.030000,191.950000,50.030000,77.490000,28.630000,247.740000
max,2017-12-29 16:00:00,176.420000,47.430000,202.680000,199.560000,121.690000,215.800000,56.530000,99.620000,32.930000,385.000000
std,NaN,28.856614,2.915722,52.093716,29.738410,23.340639,21.860902,3.686156,7.579578,3.725205,97.668462

When we work with multiple observations, we need to make sure
the data is clean and have things like numerical data, not nan observations

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1509 entries, 0 to 1508
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date_gsheets  1509 non-null   datetime64[us]
 1   AAPL          1509 non-null   float64
 2   KO            1509 non-null   float64
 3   NFLX          1509 non-null   float64
 4   BRK.B         1509 non-null   float64
 5   DIS           1509 non-null   float64
 6   IBM           1509 non-null   float64
 7   VZ            1509 non-null   float64
 8   WMT           1509 non-null   float64
 9   GE            1509 non-null   float64
 10  TSLA          1509 non-null   float64
dtypes: datetime64[us](1), float64(10)
memory usage: 129.8 KB

In [25]:
df.set_index('date_gsheets', inplace=True)

In [26]:
df.head()

,AAPL,KO,NFLX,BRK.B,DIS,IBM,VZ,WMT,GE,TSLA
date_gsheets,,,,,,,,,,
2012-01-03 16:00:00,58.75,35.07,10.32,77.68,38.31,186.30,39.73,60.33,18.36,28.08
2012-01-04 16:00:00,59.06,34.85,11.49,76.80,38.85,185.54,39.21,59.71,18.56,27.71
2012-01-05 16:00:00,59.72,34.69,11.33,76.93,39.50,184.66,38.94,59.42,18.55,27.12
2012-01-06 16:00:00,60.34,34.47,12.33,76.39,39.91,182.54,38.33,59.00,18.65,26.91
2012-01-09 16:00:00,60.25,34.47,14.03,76.29,39.75,181.59,38.37,59.18,18.86,27.25

We have to set the date as an index because, from now on, we are going to ask Python to run calculations on the entire dataframe

In [42]:
returns = df.pct_change(1)
returns.dropna(inplace=True)

In [43]:
returns.head()

,AAPL,KO,NFLX,BRK.B,DIS,IBM,VZ,WMT,GE,TSLA
date_gsheets,,,,,,,,,,
2012-01-04 16:00:00,0.005277,-0.006273,0.113372,-0.011329,0.014096,-0.004079,-0.013088,-0.010277,0.010893,-0.013177
2012-01-05 16:00:00,0.011175,-0.004591,-0.013925,0.001693,0.016731,-0.004743,-0.006886,-0.004857,-0.000539,-0.021292
2012-01-06 16:00:00,0.010382,-0.006342,0.088261,-0.007019,0.010380,-0.011481,-0.015665,-0.007068,0.005391,-0.007743
2012-01-09 16:00:00,-0.001492,0.000000,0.137875,-0.001309,-0.004009,-0.005204,0.001044,0.003051,0.011260,0.012635
2012-01-10 16:00:00,0.003485,0.005802,-0.024234,0.014812,-0.003019,-0.001542,0.005212,-0.002366,-0.007423,0.013578

In [44]:
num_stocks = 10
weights = [1 / num_stocks] * num_stocks

In [45]:
weights

[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [61]:
vcv_matrix = returns.cov(ddof=1)

In [62]:
vcv_matrix

,AAPL,KO,NFLX,BRK.B,DIS,IBM,VZ,WMT,GE,TSLA
AAPL,0.000246,0.000028,0.000059,0.000044,0.000048,0.000048,0.000027,0.000029,0.000047,0.000094
KO,0.000028,0.000075,0.000026,0.000037,0.000037,0.000032,0.000033,0.000029,0.000035,0.000038
NFLX,0.000059,0.000026,0.001063,0.000054,0.000057,0.000046,0.000015,0.000035,0.000060,0.000230
BRK.B,0.000044,0.000037,0.000054,0.000080,0.000055,0.000050,0.000038,0.000032,0.000057,0.000060
DIS,0.000048,0.000037,0.000057,0.000055,0.000132,0.000045,0.000039,0.000034,0.000058,0.000080
IBM,0.000048,0.000032,0.000046,0.000050,0.000045,0.000132,0.000035,0.000028,0.000057,0.000065
VZ,0.000027,0.000033,0.000015,0.000038,0.000039,0.000035,0.000103,0.000032,0.000044,0.000034
WMT,0.000029,0.000029,0.000035,0.000032,0.000034,0.000028,0.000032,0.000115,0.000030,0.000036
GE,0.000047,0.000035,0.000060,0.000057,0.000058,0.000057,0.000044,0.000030,0.000136,0.000066
TSLA,0.000094,0.000038,0.000230,0.000060,0.000080,0.000065,0.000034,0.000036,0.000066,0.000931

In [63]:
var_p = np.dot(np.transpose(weights),
               np.dot(vcv_matrix, weights))

In [64]:
var_p

np.float64(7.332673907420125e-05)

In [65]:
sd_p = np.sqrt(var_p)

In [66]:
sd_p

np.float64(0.00856310335533802)

In [67]:
sd_p_annual = sd_p * np.sqrt(250)

In [68]:
sd_p_annual

np.float64(0.13539455221149155)

In [69]:
individual_risks = returns.std(ddof=1) * np.sqrt(250)

In [70]:
print(individual_risks)

AAPL     0.248085
KO       0.137303
NFLX     0.515473
BRK.B    0.141077
DIS      0.181373
IBM      0.181766
VZ       0.160274
WMT      0.169337
GE       0.184540
TSLA     0.482390
dtype: float64

Just by having an equally weighted portfolio, we outperformed the risk of every single stock